// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO64scnnzM6X61N68DvWgu3YtD9GR3dUk',
    appId: '1:440969136840:web:965a5b3898e78758e1f3fd',
    messagingSenderId: '440969136840',
    projectId: 'myprojectfirebase-7fd5',
    authDomain: 'myprojectfirebase-7fd5.firebaseapp.com',
    storageBucket: 'myprojectfirebase-7fd5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiubIlLD2pgzsUT551xIwOGWvm5N9VyTI',
    appId: '1:440969136840:android:6909aaa76941b6fde1f3fd',
    messagingSenderId: '440969136840',
    projectId: 'myprojectfirebase-7fd5',
    storageBucket: 'myprojectfirebase-7fd5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgZGH9yFC802qeVh5E4G5q_z3Y3xdLJ88',
    appId: '1:440969136840:ios:b3a40c604fb922c8e1f3fd',
    messagingSenderId: '440969136840',
    projectId: 'myprojectfirebase-7fd5',
    storageBucket: 'myprojectfirebase-7fd5.firebasestorage.app',
    iosBundleId: 'com.example.pertemuan11',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgZGH9yFC802qeVh5E4G5q_z3Y3xdLJ88',
    appId: '1:440969136840:ios:b3a40c604fb922c8e1f3fd',
    messagingSenderId: '440969136840',
    projectId: 'myprojectfirebase-7fd5',
    storageBucket: 'myprojectfirebase-7fd5.firebasestorage.app',
    iosBundleId: 'com.example.pertemuan11',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDO64scnnzM6X61N68DvWgu3YtD9GR3dUk',
    appId: '1:440969136840:web:17b5224f07d52078e1f3fd',
    messagingSenderId: '440969136840',
    projectId: 'myprojectfirebase-7fd5',
    authDomain: 'myprojectfirebase-7fd5.firebaseapp.com',
    storageBucket: 'myprojectfirebase-7fd5.firebasestorage.app',
  );
}
